ip: true
success:
  words:
    - successful
    - success
    - done
    - active
    - running
    - ok
    - Ready
  color:
    green
fail:
  words:
    - failed
    - error
    - not found
    - failuire
    - NotReady
  color:
    red
other:
  words:
    - true
    - false
    - taint
  color:
    blue
