ip: true
success:
  words:
    - successful
    - success
    - done
    - active
    - running
    - ok
  color:
    green
fail:
  words:
    - failed
    - error
    - not found
    - failure
  color:
    red
other:
  words:
    - true
    - false
  color:
    blue
